apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - image: jenkins/jenkins:2.154-alpine
          name: jenkins
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 50000
              name: jnlp-port
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          volumes:
            - name: jenkins-home
              persistentVolumeClaim:
              claimName: jenkins-pvc