apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvc
spec:
  capacity:
    storage: 1024Gi # Capacidade do volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.67.207.106
    path: /share